import json
import math
import sys

srcFile = sys.argv[1]
destFile = sys.argv[2]

with open(srcFile, 'r') as starJsonFile:
    starJson = json.load(starJsonFile)

fileHeader ='''/* <editor-fold desc="MIT License">

Copyright(c) 2025 Timothy Moore

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

</editor-fold> */

// This file is generated by CreateStarCatalog.py. Do not edit!

#include "StarCatalog.h"

namespace taal
{
    const std::vector<StarCatalog::Entry> StarCatalog::catalog = {'''

with open(destFile, 'w') as cppFp:
    print(fileHeader, file=cppFp)
    first = True
    for entry in starJson:
        # Skip any entries that are e.g. just comments
        if 'hr' in entry:
            if not first:
                print(",", file=cppFp)
            first = False
            ra = math.radians(float(entry['raDeg']))
            dec = math.radians(float(entry['Dec']))
            mag = entry['magnitude'].strip()
            print("        {{{}, {:.6f}f, {:.6f}f, {}f}}".format(entry['hr'], ra, dec, mag),
                  file=cppFp, end="")
    print("};", file=cppFp)
    first = True
    print("", file=cppFp)
    print("    const std::map<uint32_t, const StarCatalog::AuxEntry> StarCatalog::auxData = {", file=cppFp)
    for entry in starJson:
        if 'hr' in entry and ('name' in entry or 'bayer' in entry or 'flamsteed' in entry or 'constellation' in entry):
            if not first:
                print(",", file=cppFp)
            first = False
            bayerName = entry.get('bayer', "")
            flamsteedName = entry.get('flamsteed', -1)
            constellation = entry.get('constellation', "")
            comment = entry.get('comment', "")
            comment = comment.replace('"', '\\"')
            print("        {{{}, {{\"{}\", {}, \"{}\", \"{}\"}}}}".format(entry['hr'],
                                                      bayerName, flamsteedName, constellation, comment),
                  file=cppFp, end="")
    print("};", file=cppFp)
    print("}", file=cppFp)
